package com.crystalark.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Size;

@ApiModel(description = "Book Details")
@Data
public class BookBaseDTO {

    @ApiModelProperty(dataType = "long", required = false, notes = "Autogenerated")
    private Long id;

    @ApiModelProperty(dataType = "String", required = true, notes = "Name should between 3-40 characters")
    @Size(min = 3, max = 40, message = "Name should between 3-40 characters")
    private String name;

    @ApiModelProperty(dataType = "String", required = true, notes = "Author name should between 3-40 characters")
    @Size(min = 3, max = 40, message = "Author name should between 3-40 characters")
    private String author;

    @ApiModelProperty(dataType = "String", notes = "Name should between 3-100 characters")
    @Size(min = 3, max = 100, message = "Name should between 3-100 characters")
    private String description;

    @ApiModelProperty(dataType = "Decimal", required = true, notes = "MRP should be >= 0.00")
    @DecimalMin(value = "0.0", message = "MRP should be >= 0.00")
    private double mrp;

    @ApiModelProperty(dataType = "String", required = true, notes = "Category should between 3-20 characters")
    @Size(min = 3, max = 20, message = "Category should between 3-20 characters")
    private String category;
}