/*
 * Copyright (c) 2019 MasterCard. All rights reserved.
 */

package com.crystalark.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.Email;
import javax.validation.constraints.Size;

@ApiModel(description = "Book Details")
@Data
public class UserBaseDTO {

    @ApiModelProperty(dataType = "long", required = false, notes = "Autogenerated")
    private Long id;

    @ApiModelProperty(dataType = "String", required = true, notes = "Name should between 3-40 characters")
    @Size(min = 3, max = 40, message = "Name should between 3-40 characters")
    private String name;

    @ApiModelProperty(dataType = "String", required = true, notes = "Address name should between 3-40 characters")
    @Size(min = 3, max = 40, message = "Address name should between 3-40 characters")
    private String address;

    @ApiModelProperty(dataType = "String", notes = "Contact should between 3-100 characters")
    @Size(min = 3, max = 100, message = "Contact should a valid email address")
    @Email
    private String contact;

    @ApiModelProperty(dataType = "String", required = true, notes = "Role should between 3-20 characters")
    @Size(min = 3, max = 20, message = "Role should be either ADMIN or GEN")
    private String role;

}
